[package]
name = "tors"
version = "0.1.0"
authors = ["Devdutt Shenoi <devdutt@outlook.in>"]
edition = "2018"
description = "A torrent client built in rust as a weekend project during the lockdown"

[dependencies]
